version: "3.7"

services:
  redis:
    image: redis
    ports:
      - 2929:6379
    command: >
      --requirepass Gokugohan
  mongo:
    image: mongo
    restart: always
    ports:
      - 29017:27017
    environment:
      MONGO_INITDB_DATABASE: aciapi_cdl
  postgres:
    image: postgres
    restart: always
    ports:
      - 6632:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Gokugohan
      - POSTGRES_DB=coupon_app
